# Generated by Django 5.0.6 on 2024-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appberita', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
